//!SET_NEW_LANGUAGE
//!SET_NEW_APPDATA
//!CHECK_MOBILE_OR_NOT
//!SET_NAVBAR_TAXI_DEALS
//!Reset Selected Points
//!GET_APP_DATA
DELETE_ITEM_FROM_SELECTEDLIST
SET_POST_CODE_ADRESSES
ADD_NEW_POINT
GET_QUOTATION
SET_TOKEN_TO_PASSENGERDETAILS
SET_SESSION_TOKEN
SET_JOURNEY_DATETIME
CHECHK_FLIGHT_WAITING_TIME
SWITCH_JOURNEY