//!Constant helpers

import { navigator } from "./navigatior";

const airportPoints = {
    IST: [
        {
            en: "Istanbul Airport To Taksim",
            tr: "İstanbul Havalimanı Taksim'e",
            es: "Aeropuerto de Estambul a Taksim",
            it: "Aeroporto di Istanbul a Taksim",
            ru: "Аэропорт Стамбула в Таксим",
            zh: "伊斯坦布尔机场到塔克西姆",
            ar: "مطار إسطنبول إلى تقسيم",
            linkUrl: "istanbul-airport-to-taksim",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/taksim.webp",
            key: "IST"
        },
        {
            en: "Istanbul Airport To Sultanahmet",
            tr: "İstanbul Havalimanı Sultanahmet'e",
            es: "Aeropuerto de Estambul a Sultanahmet",
            it: "Aeroporto di Istanbul a Sultanahmet",
            ru: "Аэропорт Стамбула в Султанахмет",
            zh: "伊斯坦布尔机场到苏丹艾哈迈德",
            ar: "مطار إسطنبول إلى السلطان أحمد",
            linkUrl: "istanbul-airport-to-sultanahmet",
            price: 100,
            key: "IST",
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/sultanahmet.webp"


        },
        {
            en: "Istanbul Airport To Kadıköy (Asian Side)",
            tr: "İstanbul Havalimanı Kadıköy (Anadolu Yakası)",
            es: "Aeropuerto de Estambul a Kadıköy (lado asiático)",
            it: "Aeroporto di Istanbul a Kadıköy (lato asiatico)",
            ru: "Аэропорт Стамбула в Кадыкёй (азиатская сторона)",
            zh: "伊斯坦布尔机场到卡德柯伊（亚洲侧）",
            ar: "مطار إسطنبول إلى كاديكوي (الجانب الآسيوي)",
            linkUrl: "istanbul-airport-to-kadikoy",
            key: "IST",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/kadikoy.webp"

        },
        {
            en: "Istanbul Airport To Beyoğlu",
            tr: "İstanbul Havalimanı Beyoğlu'na",
            es: "Aeropuerto de Estambul a Beyoğlu",
            it: "Aeroporto di Istanbul a Beyoğlu",
            ru: "Аэропорт Стамбула в Бейоглу",
            zh: "伊斯坦布尔机场到贝尤鲁",
            ar: "مطار إسطنبول إلى بيوغلو",
            linkUrl: "istanbul-airport-to-beyoglu",
            key: "IST",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/beyoglu.webp"

        },
        {
            en: "Istanbul Airport To Beşiktaş",
            tr: "İstanbul Havalimanı Beşiktaş'a",
            es: "Aeropuerto de Estambul a Beşiktaş",
            it: "Aeroporto di Istanbul a Beşiktaş",
            ru: "Аэропорт Стамбула в Бешикташ",
            zh: "伊斯坦布尔机场到贝西克塔斯",
            ar: "مطار إسطنبول إلى بشيكتاش",
            linkUrl: "istanbul-airport-to-besiktas",
            key: "IST",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/besiktas.webp"

        },
        {
            en: "Istanbul Airport To Bursa",
            tr: "İstanbul Havalimanı Bursa'ya",
            es: "Aeropuerto de Estambul a Bursa",
            it: "Aeroporto di Istanbul a Bursa",
            ru: "Аэропорт Стамбула в Бурсу",
            zh: "伊斯坦布尔机场到布尔萨",
            ar: "مطار إسطنبول إلى بورصة",
            linkUrl: "istanbul-airport-to-bursa",
            location: "Istanbul",
            key: "IST",
            price: 100,
            imageUrl: "/images/popularDestinations/istanbul/nisantasi.webp"
        },

        {
            en: "Istanbul Airport To Eminönü",
            tr: "İstanbul Havalimanı Eminönü'ne",
            es: "Aeropuerto de Estambul a Eminönü",
            it: "Aeroporto di Istanbul a Eminönü",
            ru: "Аэропорт Стамбула в Эминёню",
            zh: "伊斯坦布尔机场到埃米诺努",
            ar: "مطار إسطنبول إلى إمينونو",
            linkUrl: "istanbul-airport-to-eminonu",
            key: "IST",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/eminonu.webp"

        },
        {
            en: "Istanbul Airport To Üsküdar (Asian Side)",
            tr: "İstanbul Havalimanı Üsküdar (Anadolu Yakası)",
            es: "Aeropuerto de Estambul a Üsküdar (lado asiático)",
            it: "Aeroporto di Istanbul a Üsküdar (lato asiatico)",
            ru: "Аэропорт Стамбула в Ускюдар (азиатская сторона)",
            zh: "伊斯坦布尔机场到于斯屈达尔（亚洲侧）",
            ar: "مطار إسطنبول إلى أسكودار (الجانب الآسيوي)",
            linkUrl: "istanbul-airport-to-uskudar-asian-side",
            key: "IST",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/uskudar.webp"

        },
        {
            en: "Istanbul Airport To Levent/Maslak",
            tr: "İstanbul Havalimanı Levent/Maslak'a",
            es: "Aeropuerto de Estambul a Levent/Maslak",
            it: "Aeroporto di Istanbul a Levent/Maslak",
            ru: "Аэропорт Стамбула в Левент/Маслак",
            zh: "伊斯坦布尔机场到勒文特/马斯拉克",
            ar: "مطار إسطنبول إلى ليفنت/ماسلاك",
            linkUrl: "istanbul-airport-to-levent-maslak",
            key: "IST",
            price: 100,
            location: "Istanbul",

        },
        {
            en: "Istanbul Airport To Ortaköy",
            tr: "İstanbul Havalimanı Ortaköy'e",
            es: "Aeropuerto de Estambul a Ortaköy",
            it: "Aeroporto di Istanbul a Ortaköy",
            ru: "Аэропорт Стамбула в Ортакёй",
            zh: "伊斯坦布尔机场到奥塔科伊",
            ar: "مطار إسطنبول إلى أورتاكوي",
            linkUrl: "istanbul-airport-to-ortakoy",
            key: "IST",
            price: 100,
            location: "Istanbul",

        },
        {
            en: "Istanbul Airport To Sapanca",
            tr: "İstanbul Havalimanı Sapanca'ya",
            es: "Aeropuerto de Estambul a Sapanca",
            it: "Aeroporto di Istanbul a Sapanca",
            ru: "Аэропорт Стамбула в Сапанджу",
            zh: "伊斯坦布尔机场到萨潘贾",
            ar: "مطار إسطنبول إلى سبانجا",
            linkUrl: "istanbul-airport-to-sapanca",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
        {
            en: "Istanbul Airport To Nişantaşı",
            tr: "İstanbul Havalimanı Nişantaşı'na",
            es: "Aeropuerto de Estambul a Nişantaşı",
            it: "Aeroporto di Istanbul a Nişantaşı",
            ru: "Аэропорт Стамбула в Нишанташи",
            zh: "伊斯坦布尔机场到尼尚塔西",
            ar: "مطار إسطنبول إلى نيشان تاشي",
            linkUrl: "istanbul-airport-to-nisantasi",
            key: "IST",
            price: 100,
            location: "Istanbul",


        },
        {
            en: "Istanbul Airport To Yalova",
            tr: "İstanbul Havalimanı Yalova'ya",
            es: "Aeropuerto de Estambul a Yalova",
            it: "Aeroporto di Istanbul a Yalova",
            ru: "Аэропорт Стамбула в Ялову",
            zh: "伊斯坦布尔机场到亚洛瓦",
            ar: "مطار إسطنبول إلى يالوفا",
            linkUrl: "istanbul-airport-to-yalova",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
        {
            en: "Istanbul Airport To Kocaeli (Izmit)",
            tr: "İstanbul Havalimanı Kocaeli (İzmit)'e",
            es: "Aeropuerto de Estambul a Kocaeli (Izmit)",
            it: "Aeroporto di Istanbul a Kocaeli (Izmit)",
            ru: "Аэропорт Стамбула в Коджаэли (Измит)",
            zh: "伊斯坦布尔机场到科贾埃利（伊兹密特）",
            ar: "مطار إسطنبول إلى كوجالي (إزميت)",
            linkUrl: "istanbul-airport-to-kocaeli-izmit",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
        {
            en: "Istanbul Airport To Şile and Ağva",
            tr: "İstanbul Havalimanı Şile ve Ağva'ya",
            es: "Aeropuerto de Estambul a Şile y Ağva",
            it: "Aeroporto di Istanbul a Şile e Ağva",
            ru: "Аэропорт Стамбула в Шиле и Агва",
            zh: "伊斯坦布尔机场到希勒和阿格瓦",
            ar: "مطار إسطنبول إلى شيلا وأغفا",
            linkUrl: "istanbul-airport-to-sile-and-agva",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
        {
            en: "Istanbul Airport To Edirne",
            tr: "İstanbul Havalimanı Edirne'ye",
            es: "Aeropuerto de Estambul a Edirne",
            it: "Aeroporto di Istanbul a Edirne",
            ru: "Аэропорт Стамбула в Эдирне",
            zh: "伊斯坦布尔机场到埃迪尔内",
            ar: "مطار إسطنبول إلى أدرنة",
            linkUrl: "istanbul-airport-to-edirne",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
        {
            en: "Istanbul Airport To Tekirdağ",
            tr: "İstanbul Havalimanı Tekirdağ'a",
            es: "Aeropuerto de Estambul a Tekirdağ",
            it: "Aeroporto di Istanbul a Tekirdağ",
            ru: "Аэропорт Стамбула в Текирдаг",
            zh: "伊斯坦布尔机场到泰基尔达",
            ar: "مطار إسطنبول إلى تكيرداغ",
            linkUrl: "istanbul-airport-to-tekirdag",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
        {
            en: "Istanbul Airport To Çanakkale",
            tr: "İstanbul Havalimanı Çanakkale'ye",
            es: "Aeropuerto de Estambul a Çanakkale",
            it: "Aeroporto di Istanbul a Çanakkale",
            ru: "Аэропорт Стамбула в Чанаккале",
            zh: "伊斯坦布尔机场到恰纳卡莱",
            ar: "مطار إسطنبول إلى جناق قلعة",
            linkUrl: "istanbul-airport-to-canakkale",
            location: "Istanbul",
            key: "IST",
            price: 100,
        },
    ],
    SAW: [
        {
            en: "Sabiha Gökçen Airport To Taksim",
            tr: "Sabiha Gökçen Havalimanı Taksim'e",
            es: "Aeropuerto de Sabiha Gökçen a Taksim",
            it: "Aeroporto di Sabiha Gökçen a Taksim",
            ru: "Аэропорт Сабиха Гёкчен в Таксим",
            zh: "萨比哈·格克琴机场到塔克西姆",
            ar: "مطار صبيحة كوكجن إلى تقسيم",
            linkUrl: "sabiha-gokcen-airport-to-taksim",
            key: "SAW",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/taksim.webp"

        },
        {
            en: "Sabiha Gökçen Airport To Sultanahmet",
            tr: "Sabiha Gökçen Havalimanı Sultanahmet'e",
            es: "Aeropuerto de Sabiha Gökçen a Sultanahmet",
            it: "Aeroporto di Sabiha Gökçen a Sultanahmet",
            ru: "Аэропорт Сабиха Гёкчен в Султанахмет",
            zh: "萨比哈·格克琴机场到苏丹艾哈迈德",
            ar: "مطار صبيحة كوكجن إلى السلطان أحمد",
            linkUrl: "sabiha-gokcen-airport-to-sultanahmet",
            key: "SAW",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/sultanahmet.webp"

        },
        {
            en: "Sabiha Gökçen Airport To Kadıköy",
            tr: "Sabiha Gökçen Havalimanı Kadıköy'e",
            es: "Aeropuerto de Sabiha Gökçen a Kadıköy",
            it: "Aeroporto di Sabiha Gökçen a Kadıköy",
            ru: "Аэропорт Сабиха Гёкчен в Кадыкёй",
            zh: "萨比哈·格克琴机场到卡德柯伊",
            ar: "مطار صبيحة كوكجن إلى كاديكوي",
            linkUrl: "sabiha-gokcen-airport-to-kadikoy",
            key: "SAW",
            price: 100,
            location: "Istanbul",
            imageUrl: "/images/popularDestinations/istanbul/kadikoy.webp"

        },
        {
            en: "Sabiha Gökçen Airport To Beyoğlu",
            tr: "Sabiha Gökçen Havalimanı Beyoğlu'na",
            es: "Aeropuerto de Sabiha Gökçen a Beyoğlu",
            it: "Aeroporto di Sabiha Gökçen a Beyoğlu",
            ru: "Аэропорт Сабиха Гёкчен в Бейоглу",
            zh: "萨比哈·格克琴机场到贝尤鲁",
            ar: "مطار صبيحة كوكجن إلى بيوغلو",
            key: "SAW",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-beyoglu",
            imageUrl: "/images/popularDestinations/istanbul/beyoglu.webp",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Beşiktaş",
            tr: "Sabiha Gökçen Havalimanı Beşiktaş'a",
            es: "Aeropuerto de Sabiha Gökçen a Beşiktaş",
            it: "Aeroporto di Sabiha Gökçen a Beşiktaş",
            ru: "Аэропорт Сабиха Гёкчен в Бешикташ",
            zh: "萨比哈·格克琴机场到贝西克塔斯",
            ar: "مطار صبيحة كوكجن إلى بشيكتاش",
            linkUrl: "sabiha-gokcen-airport-to-besiktas",
            location: "Istanbul",
            key: "SAW",
            price: 100,
            imageUrl: "/images/popularDestinations/istanbul/besiktas.webp"

        },



        {
            en: "Sabiha Gökçen Airport To Üsküdar",
            tr: "Sabiha Gökçen Havalimanı Üsküdar'a",
            es: "Aeropuerto de Sabiha Gökçen a Üsküdar",
            it: "Aeroporto di Sabiha Gökçen a Üsküdar",
            ru: "Аэропорт Сабиха Гёкчен в Ускюдар",
            zh: "萨比哈·格克琴机场到于斯屈达尔",
            location: "Istanbul",
            ar: "مطار صبيحة كوكجن إلى أسكودار",
            linkUrl: "sabiha-gokcen-airport-to-uskudar",
            imageUrl: "/images/popularDestinations/istanbul/uskudar.webp",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Eminönü",
            tr: "Sabiha Gökçen Havalimanı Eminönü'ne",
            es: "Aeropuerto de Sabiha Gökçen a Eminönü",
            it: "Aeroporto di Sabiha Gökçen a Eminönü",
            ru: "Аэропорт Сабиха Гёкчен в Эминёню",
            zh: "萨比哈·格克琴机场到埃米诺努",
            ar: "مطار صبيحة كوكجن إلى إمينونو",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-eminonu",
            key: "SAW",
            price: 100,
            imageUrl: "/images/popularDestinations/istanbul/eminonu.webp"

        },
        {
            en: "Sabiha Gökçen Airport To Nişantaşı",
            tr: "Sabiha Gökçen Havalimanı Nişantaşı'na",
            es: "Aeropuerto de Sabiha Gökçen a Nişantaşı",
            it: "Aeroporto di Sabiha Gökçen a Nişantaşı",
            ru: "Аэропорт Сабиха Гёкчен в Нишанташи",
            zh: "萨比哈·格克琴机场到尼尚塔西",
            ar: "مطار صبيحة كوكجن إلى نيشان تاشي",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-nisantasi",
            key: "SAW",
            price: 100,
            imageUrl: "/images/popularDestinations/istanbul/nisantasi.webp"

        },
        {
            en: "Sabiha Gökçen Airport To Levent/Maslak",
            tr: "Sabiha Gökçen Havalimanı Levent/Maslak'a",
            es: "Aeropuerto de Sabiha Gökçen a Levent/Maslak",
            it: "Aeroporto di Sabiha Gökçen a Levent/Maslak",
            ru: "Аэропорт Сабиха Гёкчен в Левент/Маслак",
            zh: "萨比哈·格克琴机场到勒文特/马斯拉克",
            ar: "مطار صبيحة كوكجن إلى ليفنت/ماسلاك",
            linkUrl: "sabiha-gokcen-airport-to-levent-maslak",
            key: "SAW",

            location: "Istanbul",
            price: 100,
        },

        {
            en: "Sabiha Gökçen Airport To Ortaköy",
            tr: "Sabiha Gökçen Havalimanı Ortaköy'e",
            es: "Aeropuerto de Sabiha Gökçen a Ortaköy",
            it: "Aeroporto di Sabiha Gökçen a Ortaköy",
            ru: "Аэропорт Сабиха Гёкчен в Ортакёй",
            zh: "萨比哈·格克琴机场到奥塔科伊",
            ar: "مطار صبيحة كوكجن إلى أورتاكوي",
            linkUrl: "sabiha-gokcen-airport-to-ortakoy",
            location: "Istanbul",
            key: "SAW",
            price: 100,
        },


        {
            en: "Sabiha Gökçen Airport To Sapanca",
            tr: "Sabiha Gökçen Havalimanı Sapanca'ya",
            es: "Aeropuerto de Sabiha Gökçen a Sapanca",
            it: "Aeroporto di Sabiha Gökçen a Sapanca",
            ru: "Аэропорт Сабиха Гёкчен в Сапанджу",
            zh: "萨比哈·格克琴机场到萨潘贾",
            ar: "مطار صبيحة كوكجن إلى سبانجا",
            linkUrl: "sabiha-gokcen-airport-to-sapanca",
            location: "Istanbul",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Bursa",
            tr: "Sabiha Gökçen Havalimanı Bursa'ya",
            es: "Aeropuerto de Sabiha Gökçen a Bursa",
            it: "Aeroporto di Sabiha Gökçen a Bursa",
            ru: "Аэропорт Сабиха Гёкчен в Бурсу",
            zh: "萨比哈·格克琴机场到布尔萨",
            ar: "مطار صبيحة كوكجن إلى بورصة",
            linkUrl: "sabiha-gokcen-airport-to-bursa",
            location: "Istanbul",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Yalova",
            tr: "Sabiha Gökçen Havalimanı Yalova'ya",
            es: "Aeropuerto de Sabiha Gökçen a Yalova",
            it: "Aeroporto di Sabiha Gökçen a Yalova",
            ru: "Аэропорт Сабиха Гёкчен в Ялову",
            zh: "萨比哈·格克琴机场到亚洛瓦",
            ar: "مطار صبيحة كوكجن إلى يالوفا",
            linkUrl: "sabiha-gokcen-airport-to-yalova",
            location: "Istanbul",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Kocaeli (Izmit)",
            tr: "Sabiha Gökçen Havalimanı Kocaeli (İzmit)'e",
            es: "Aeropuerto de Sabiha Gökçen a Kocaeli (Izmit)",
            it: "Aeroporto di Sabiha Gökçen a Kocaeli (Izmit)",
            ru: "Аэропорт Сабиха Гёкчен в Коджаэли (Измит)",
            zh: "萨比哈·格克琴机场到科贾埃利（伊兹密特）",
            ar: "مطار صبيحة كوكجن إلى كوجالي (إزميت)",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-kocaeli-izmit",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Şile and Ağva",
            tr: "Sabiha Gökçen Havalimanı Şile ve Ağva'ya",
            es: "Aeropuerto de Sabiha Gökçen a Şile y Ağva",
            it: "Aeroporto di Sabiha Gökçen a Şile e Ağva",
            ru: "Аэропорт Сабиха Гёкчен в Шиле и Агва",
            zh: "萨比哈·格克琴机场到希勒和阿格瓦",
            ar: "مطار صبيحة كوكجن إلى شيلا وأغفا",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-sile-and-agva",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Edirne",
            tr: "Sabiha Gökçen Havalimanı Edirne'ye",
            es: "Aeropuerto de Sabiha Gökçen a Edirne",
            it: "Aeroporto di Sabiha Gökçen a Edirne",
            ru: "Аэропорт Сабиха Гёкчен в Эдирне",
            zh: "萨比哈·格克琴机场到埃迪尔内",
            ar: "مطار صبيحة كوكجن إلى أدرنة",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-edirne",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Tekirdağ",
            tr: "Sabiha Gökçen Havalimanı Tekirdağ'a",
            es: "Aeropuerto de Sabiha Gökçen a Tekirdağ",
            it: "Aeroporto di Sabiha Gökçen a Tekirdağ",
            ru: "Аэропорт Сабиха Гёкчен в Текирдаг",
            zh: "萨比哈·格克琴机场到泰基尔达",
            ar: "مطار صبيحة كوكجن إلى تكيرداغ",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-tekirdag",
            key: "SAW",
            price: 100,
        },
        {
            en: "Sabiha Gökçen Airport To Çanakkale",
            tr: "Sabiha Gökçen Havalimanı Çanakkale'ye",
            es: "Aeropuerto de Sabiha Gökçen a Çanakkale",
            it: "Aeroporto di Sabiha Gökçen a Çanakkale",
            ru: "Аэропорт Сабиха Гёкчен в Чанаккале",
            zh: "萨比哈·格克琴机场到恰纳卡莱",
            ar: "مطار صبيحة كوكجن إلى جناق قلعة",
            location: "Istanbul",
            linkUrl: "sabiha-gokcen-airport-to-canakkale",
            key: "SAW",
            price: 100,
        },
    ],
    AYT: [
        {
            en: "Antalya Airport To Lara Beach",
            tr: "Antalya Havalimanı Lara Plajı'na",
            es: "Aeropuerto de Antalya a Lara Beach",
            it: "Aeroporto di Antalya a Lara Beach",
            ru: "Аэропорт Анталии до пляжа Лара",
            zh: "安塔利亚机场到拉拉海滩",
            ar: "مطار أنطاليا إلى شاطئ لارا",
            linkUrl: "antalya-airport-to-lara-beach",
            price: 100,
            key: "AYT",
            location: "Antalya",
            imageUrl: "/images/popularDestinations/antalya/lara.webp"


        },

        {
            en: "Antalya Airport To Antalya City Center (Kaleici)",
            tr: "Antalya Havalimanı Antalya Şehir Merkezi (Kaleiçi)'ne",
            es: "Aeropuerto de Antalya al Centro de la Ciudad de Antalya (Kaleici)",
            it: "Aeroporto di Antalya al Centro Città (Kaleici)",
            ru: "Аэропорт Анталии до центра города Анталия (Калеичи)",
            zh: "安塔利亚机场到安塔利亚市中心（卡莱伊奇）",
            ar: "مطار أنطاليا إلى مركز مدينة أنطاليا (كاليتشي)",
            location: "Antalya",
            linkUrl: "antalya-airport-to-antalya-city-center-kaleici",
            key: "AYT",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/kaleici.webp"

        },
        {
            en: "Antalya Airport To Belek",
            tr: "Antalya Havalimanı Belek'e",
            es: "Aeropuerto de Antalya a Belek",
            it: "Aeroporto di Antalya a Belek",
            ru: "Аэропорт Анталии до Белека",
            zh: "安塔利亚机场到贝莱克",
            ar: "مطار أنطاليا إلى بيليك",
            location: "Antalya",
            linkUrl: "antalya-airport-to-belek",
            key: "AYT",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/belek.webp"
        },
        {
            en: "Antalya Airport To Kemer",
            tr: "Antalya Havalimanı Kemer'e",
            es: "Aeropuerto de Antalya a Kemer",
            it: "Aeroporto di Antalya a Kemer",
            ru: "Аэропорт Анталии до Кемера",
            zh: "安塔利亚机场到凯梅尔",
            ar: "مطار أنطاليا إلى كيمير",
            linkUrl: "antalya-airport-to-kemer",
            location: "Antalya",
            key: "AYT",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/kemer.webp"

        },
        {
            en: "Antalya Airport To Side",
            tr: "Antalya Havalimanı Side'ye",
            es: "Aeropuerto de Antalya a Side",
            it: "Aeroporto di Antalya a Side",
            ru: "Аэропорт Анталии до Сиде",
            zh: "安塔利亚机场到西德",
            ar: "مطار أنطاليا إلى سايد",
            key: "AYT",
            location: "Antalya",
            linkUrl: "antalya-airport-to-side",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/side.webp"

        },
        {
            en: "Antalya Airport To Manavgat",
            tr: "Antalya Havalimanı Manavgat'a",
            es: "Aeropuerto de Antalya a Manavgat",
            it: "Aeroporto di Antalya a Manavgat",
            ru: "Аэропорт Анталии до Манавгата",
            zh: "安塔利亚机场到马纳夫加特",
            ar: "مطار أنطاليا إلى مانافجات",
            linkUrl: "antalya-airport-to-manavgat",
            location: "Antalya",
            key: "AYT",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/manavgat.webp"

        },
        {
            en: "Antalya Airport To Kas",
            tr: "Antalya Havalimanı Kaş'a",
            es: "Aeropuerto de Antalya a Kas",
            it: "Aeroporto di Antalya a Kas",
            ru: "Аэропорт Анталии до Каша",
            zh: "安塔利亚机场到卡斯",
            ar: "مطار أنطاليا إلى كاش",
            location: "Antalya",
            linkUrl: "antalya-airport-to-kas",
            key: "AYT",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/kas.webp"

        },
        {
            en: "Antalya Airport To Patara",
            tr: "Antalya Havalimanı Patara'ya",
            es: "Aeropuerto de Antalya a Patara",
            it: "Aeroporto di Antalya a Patara",
            ru: "Аэропорт Анталии до Патары",
            zh: "安塔利亚机场到帕塔拉",
            ar: "مطار أنطاليا إلى باتارا",
            location: "Antalya",
            linkUrl: "antalya-airport-to-patara",
            key: "AYT",
            price: 100,
            imageUrl: "/images/popularDestinations/antalya/patara-antalya.webp"

        },
        {
            en: "Antalya Airport To Konyaalti",
            tr: "Antalya Havalimanı Konyaaltı'na",
            es: "Aeropuerto de Antalya a Konyaalti",
            it: "Aeroporto di Antalya a Konyaalti",
            ru: "Аэропорт Анталии до Коньяалты",
            zh: "安塔利亚机场到科尼亚尔蒂",
            ar: "مطار أنطاليا إلى كونيالتي",
            linkUrl: "antalya-airport-to-konyaalti",
            location: "Antalya",
            key: "AYT",

            price: 100,
        },
        {
            en: "Antalya Airport To Alanya",
            tr: "Antalya Havalimanı Alanya'ya",
            es: "Aeropuerto de Antalya a Alanya",
            it: "Aeroporto di Antalya a Alanya",
            ru: "Аэропорт Анталии до Алании",
            zh: "安塔利亚机场到阿拉尼亚",
            ar: "مطار أنطاليا إلى ألانيا",
            location: "Antalya",
            linkUrl: "antalya-airport-to-alanya",
            key: "AYT",
            price: 100,
        },
        {
            en: "Antalya Airport To Cirali",
            tr: "Antalya Havalimanı Çıralı'ya",
            es: "Aeropuerto de Antalya a Cirali",
            it: "Aeroporto di Antalya a Cirali",
            ru: "Аэропорт Анталии до Чиралы",
            zh: "安塔利亚机场到奇拉利",
            location: "Antalya",
            ar: "مطار أنطاليا إلى تشيرالي",
            linkUrl: "antalya-airport-to-cirali",
            key: "AYT",
            price: 100,
        },

        {
            en: "Antalya Airport To Demre",
            tr: "Antalya Havalimanı Demre'ye",
            es: "Aeropuerto de Antalya a Demre",
            it: "Aeroporto di Antalya a Demre",
            ru: "Аэропорт Анталии до Демре",
            zh: "安塔利亚机场到代姆雷",
            location: "Antalya",
            ar: "مطار أنطاليا إلى دمرة",
            linkUrl: "antalya-airport-to-demre",
            key: "AYT",
            price: 100,
        },
        {
            en: "Antalya Airport To Finike",
            tr: "Antalya Havalimanı Finike'ye",
            es: "Aeropuerto de Antalya a Finike",
            it: "Aeroporto di Antalya a Finike",
            ru: "Аэропорт Анталии до Финике",
            zh: "安塔利亚机场到费尼凯",
            ar: "مطار أنطاليا إلى فينيكا",
            linkUrl: "antalya-airport-to-finike",
            price: 100,
            key: "AYT",
            location: "Antalya",
        },
        {
            en: "Antalya Airport To Goynuk",
            tr: "Antalya Havalimanı Göynük'e",
            es: "Aeropuerto de Antalya a Goynuk",
            it: "Aeroporto di Antalya a Goynuk",
            ru: "Аэропорт Анталии до Гейнюка",
            zh: "安塔利亚机场到戈伊努克",
            ar: "مطار أنطاليا إلى غوينوك",
            location: "Antalya",
            linkUrl: "antalya-airport-to-goynuk",
            key: "AYT",
            price: 100,
        },
        {
            en: "Antalya Airport To Olympos",
            tr: "Antalya Havalimanı Olimpos'a",
            es: "Aeropuerto de Antalya a Olympos",
            it: "Aeroporto di Antalya a Olympos",
            ru: "Аэропорт Анталии до Олимпоса",
            zh: "安塔利亚机场到奥林波斯",
            ar: "مطار أنطاليا إلى أوليمبوس",
            location: "Antalya",
            linkUrl: "antalya-airport-to-olympos",
            key: "AYT",
            price: 100,
        },
        {
            en: "Antalya Airport To Adrasan",
            tr: "Antalya Havalimanı Adrasan'a",
            es: "Aeropuerto de Antalya a Adrasan",
            it: "Aeroporto di Antalya a Adrasan",
            ru: "Аэропорт Анталии до Адрасана",
            zh: "安塔利亚机场到阿德拉桑",
            ar: "مطار أنطاليا إلى أدراسان",
            location: "Antalya",
            linkUrl: "antalya-airport-to-adrasan",
            key: "AYT",
            price: 100,
        },
        {
            en: "Antalya Airport To Tekirova",
            tr: "Antalya Havalimanı Tekirova'ya",
            es: "Aeropuerto de Antalya a Tekirova",
            it: "Aeroporto di Antalya a Tekirova",
            ru: "Аэропорт Анталии до Текерова",
            zh: "安塔利亚机场到特基罗瓦",
            location: "Antalya",
            ar: "مطار أنطاليا إلى تيكيروفا",
            linkUrl: "antalya-airport-to-tekirova",
            key: "AYT",
            price: 100,
        },
        {
            en: "Antalya Airport To Beldibi",
            tr: "Antalya Havalimanı Beldibi'ne",
            es: "Aeropuerto de Antalya a Beldibi",
            it: "Aeroporto di Antalya a Beldibi",
            ru: "Аэропорт Анталии до Бельдиби",
            zh: "安塔利亚机场到贝尔迪比",
            location: "Antalya",
            ar: "مطار أنطاليا إلى بيلديبي",
            key: "AYT",
            linkUrl: "antalya-airport-to-beldibi",
            price: 100,
        },
    ],
    DLM: [
        {
            en: "Dalaman Airport To Oludeniz",
            tr: "Dalaman Havalimanı Ölüdeniz'e",
            es: "Aeropuerto de Dalaman a Oludeniz",
            it: "Aeroporto di Dalaman a Oludeniz",
            ru: "Аэропорт Даламан до Олюдениза",
            zh: "达拉曼机场到厄吕代尼兹",
            ar: "مطار دالامان إلى أولودينيز",
            linkUrl: "dalaman-airport-to-oludeniz",
            location: "Dalaman",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/oludeniz.webp"

        },
        {
            en: "Dalaman Airport To Fethiye Town Center",
            tr: "Dalaman Havalimanı Fethiye Şehir Merkezi'ne",
            es: "Aeropuerto de Dalaman al Centro de Fethiye",
            it: "Aeroporto di Dalaman al Centro di Fethiye",
            ru: "Аэропорт Даламан до центра Фетхие",
            zh: "达拉曼机场到费特希耶市中心",
            ar: "مطار دالامان إلى وسط مدينة فتحية",
            linkUrl: "dalaman-airport-to-fethiye-town-center",
            key: "DLM",
            price: 100,
            location: "Dalaman",
            imageUrl: "/images/popularDestinations/fethiye/fethiye.webp"

        },
        {
            en: "Dalaman Airport To Faralya (Butterfly Valley)",
            tr: "Dalaman Havalimanı Faralya (Kelebekler Vadisi)'ne",
            es: "Aeropuerto de Dalaman a Faralya (Valle de las Mariposas)",
            it: "Aeroporto di Dalaman a Faralya (Valle delle Farfalle)",
            ru: "Аэропорт Даламан до Фаральи (Долина бабочек)",
            zh: "达拉曼机场到法拉利亚（蝴蝶谷）",
            ar: "مطار دالامان إلى فاراليا (وادي الفراشات)",
            linkUrl: "dalaman-airport-to-faralya-butterfly-valley",
            location: "Dalaman",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/marmaris.webp"

        },
        {
            en: "Dalaman Airport To Gocek",
            tr: "Dalaman Havalimanı Göcek'e",
            es: "Aeropuerto de Dalaman a Gocek",
            it: "Aeroporto di Dalaman a Gocek",
            ru: "Аэропорт Даламан до Гёчека",
            zh: "达拉曼机场到戈切克",
            ar: "مطار دالامان إلى جوتشيك",
            linkUrl: "dalaman-airport-to-gocek",
            location: "Dalaman",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/gocek.webp"

        },
        {
            en: "Dalaman Airport To Hisaronu",
            tr: "Dalaman Havalimanı Hisarönü'ne",
            es: "Aeropuerto de Dalaman a Hisaronu",
            it: "Aeroporto di Dalaman a Hisaronu",
            ru: "Аэропорт Даламан до Хисарёню",
            zh: "达拉曼机场到希萨鲁努",
            ar: "مطار دالامان إلى هيسارونو",
            location: "Dalaman",
            linkUrl: "dalaman-airport-to-hisaronu",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/hisaronu.webp"

        },
        {
            en: "Dalaman Airport To Calis Beach",
            tr: "Dalaman Havalimanı Çalış Plajı'na",
            es: "Aeropuerto de Dalaman a la Playa de Calis",
            it: "Aeroporto di Dalaman alla Spiaggia di Calis",
            ru: "Аэропорт Даламан до пляжа Чалиш",
            zh: "达拉曼机场到卡利斯海滩",
            ar: "مطار دالامان إلى شاطئ كاليس",
            linkUrl: "dalaman-airport-to-calis-beach",
            location: "Dalaman",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/dalaman.webp"

        },

        {
            en: "Dalaman Airport To Kayakoy",
            tr: "Dalaman Havalimanı Kayaköy'e",
            es: "Aeropuerto de Dalaman a Kayakoy",
            it: "Aeroporto di Dalaman a Kayakoy",
            ru: "Аэропорт Даламан до Каякёй",
            zh: "达拉曼机场到卡亚克伊",
            ar: "مطار دالامان إلى كاياكوي",
            linkUrl: "dalaman-airport-to-kayakoy",
            location: "Dalaman",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/fethiye2.webp"

        },


        {
            en: "Dalaman Airport To Kabak",
            tr: "Dalaman Havalimanı Kabak'a",
            es: "Aeropuerto de Dalaman a Kabak",
            it: "Aeroporto di Dalaman a Kabak",
            ru: "Аэропорт Даламан до Кабака",
            zh: "达拉曼机场到卡巴克",
            ar: "مطار دالامان إلى كباك",
            linkUrl: "dalaman-airport-to-kabak",
            location: "Dalaman",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/fethiye3.webp"

        },
        {
            en: "Dalaman Airport To Yanıklar",
            tr: "Dalaman Havalimanı Yanıklar'a",
            es: "Aeropuerto de Dalaman a Yanıklar",
            it: "Aeroporto di Dalaman a Yanıklar",
            ru: "Аэропорт Даламан до Яныклар",
            zh: "达拉曼机场到亚尼克拉尔",
            ar: "مطار دالامان إلى يانيكلار",
            location: "Dalaman",
            linkUrl: "dalaman-airport-to-yaniklar",
            key: "DLM",
            price: 100,
            imageUrl: "/images/popularDestinations/fethiye/fethiye4.webp"

        },
        {
            en: "Dalaman Airport To Sarigerme",
            tr: "Dalaman Havalimanı Sarıgerme'ye",
            es: "Aeropuerto de Dalaman a Sarigerme",
            it: "Aeroporto di Dalaman a Sarigerme",
            ru: "Аэропорт Даламан до Сарыгерме",
            zh: "达拉曼机场到萨里格尔梅",
            ar: "مطار دالامان إلى ساريجيرم",
            location: "Dalaman",
            linkUrl: "dalaman-airport-to-sarigerme",
            key: "DLM",
            price: 100,
        },
        {
            en: "Dalaman Airport To Uzumlu",
            tr: "Dalaman Havalimanı Üzümlü'ye",
            es: "Aeropuerto de Dalaman a Uzumlu",
            it: "Aeroporto di Dalaman a Uzumlu",
            ru: "Аэропорт Даламан до Узюмлю",
            zh: "达拉曼机场到于祖姆鲁",
            location: "Dalaman",
            ar: "مطار دالامان إلى أوزوملو",
            linkUrl: "dalaman-airport-to-uzumlu",
            key: "DLM",
            price: 100,
        },
        {
            en: "Dalaman Airport To Kalkan",
            tr: "Dalaman Havalimanı Kalkan'a",
            es: "Aeropuerto de Dalaman a Kalkan",
            it: "Aeroporto di Dalaman a Kalkan",
            ru: "Аэропорт Даламан до Калкана",
            zh: "达拉曼机场到卡尔坎",
            ar: "مطار دالامان إلى كالكان",
            location: "Dalaman",
            linkUrl: "dalaman-airport-to-kalkan",
            key: "DLM",
            price: 100,
        },
        {
            en: "Dalaman Airport To Patara",
            tr: "Dalaman Havalimanı Patara'ya",
            es: "Aeropuerto de Dalaman a Patara",
            it: "Aeroporto di Dalaman a Patara",
            ru: "Аэропорт Даламан до Патары",
            zh: "达拉曼机场到帕塔拉",
            ar: "مطار دالامان إلى باتارا",
            location: "Dalaman",
            linkUrl: "dalaman-airport-to-patara",
            key: "DLM",
            price: 100,
        },
        {
            en: "Dalaman Airport To Dalyan",
            tr: "Dalaman Havalimanı Dalyan'a",
            es: "Aeropuerto de Dalaman a Dalyan",
            it: "Aeroporto di Dalaman a Dalyan",
            ru: "Аэропорт Даламан до Дальяна",
            zh: "达拉曼机场到达利安",
            ar: "مطار دالامان إلى داليان",
            location: "Dalaman",
            linkUrl: "dalaman-airport-to-dalyan",
            key: "DLM",
            price: 100,
        },
    ],
    BJV: [
        {
            en: "Bodrum Airport To Bodrum Town Center",
            tr: "Bodrum Havalimanı Bodrum Şehir Merkezi'ne",
            es: "Aeropuerto de Bodrum al Centro de la Ciudad de Bodrum",
            it: "Aeroporto di Bodrum al Centro Città di Bodrum",
            ru: "Аэропорт Бодрум до центра города Бодрум",
            zh: "博德鲁姆机场到博德鲁姆市中心",
            ar: "مطار بودروم إلى وسط مدينة بودروم",
            linkUrl: "bodrum-airport-to-bodrum-town-center",
            key: "BJV",
            price: 100,
            location: "Bodrum",
            imageUrl: "/images/popularDestinations/bodrum/akvaryumKoyu.webp"


        },
        {
            en: "Bodrum Airport To Gumbet",
            tr: "Bodrum Havalimanı Gümbet'e",
            es: "Aeropuerto de Bodrum a Gumbet",
            it: "Aeroporto di Bodrum a Gumbet",
            ru: "Аэропорт Бодрум до Гюмбета",
            zh: "博德鲁姆机场到居姆贝特",
            location: "Bodrum",
            ar: "مطار بودروم إلى غومبيت",
            linkUrl: "bodrum-airport-to-gumbet",
            key: "BJV",
            price: 100,
            imageUrl: "/images/popularDestinations/bodrum/bodrum2.webp"

        },
        {
            en: "Bodrum Airport To Bitez",
            tr: "Bodrum Havalimanı Bitez'e",
            es: "Aeropuerto de Bodrum a Bitez",
            it: "Aeroporto di Bodrum a Bitez",
            ru: "Аэропорт Бодрум до Битеза",
            zh: "博德鲁姆机场到比特兹",
            ar: "مطار بودروم إلى بيتز",
            linkUrl: "bodrum-airport-to-bitez",
            key: "BJV",
            price: 100,
            location: "Bodrum",
            imageUrl: "/images/popularDestinations/bodrum/bodrum3.webp"

        },
        {
            en: "Bodrum Airport To Torba",
            tr: "Bodrum Havalimanı Torba'ya",
            es: "Aeropuerto de Bodrum a Torba",
            it: "Aeroporto di Bodrum a Torba",
            ru: "Аэропорт Бодрум до Торбы",
            zh: "博德鲁姆机场到托尔巴",
            ar: "مطار بودروم إلى توربا",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-torba",
            key: "BJV",
            price: 100,
            imageUrl: "/images/popularDestinations/bodrum/bodrum4.webp"

        },
        {
            en: "Bodrum Airport To Turgutreis",
            tr: "Bodrum Havalimanı Turgutreis'e",
            es: "Aeropuerto de Bodrum a Turgutreis",
            it: "Aeroporto di Bodrum a Turgutreis",
            ru: "Аэропорт Бодрум до Тургутрейса",
            zh: "博德鲁姆机场到图尔古特雷伊斯",
            ar: "مطار بودروم إلى تورغوتريس",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-turgutreis",
            key: "BJV",
            price: 100,
            imageUrl: "/images/popularDestinations/bodrum/bodrum5.webp"

        },
        {
            en: "Bodrum Airport To Yalikavak",
            tr: "Bodrum Havalimanı Yalıkavak'a",
            es: "Aeropuerto de Bodrum a Yalikavak",
            it: "Aeroporto di Bodrum a Yalikavak",
            ru: "Аэропорт Бодрум до Ялыкавак",
            zh: "博德鲁姆机场到亚利卡瓦克",
            ar: "مطار بودروم إلى ياليكافاك",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-yalikavak",
            key: "BJV",
            price: 100,
            imageUrl: "/images/popularDestinations/bodrum/bodrum6.webp"

        },
        {
            en: "Bodrum Airport To Golturkbuku",
            tr: "Bodrum Havalimanı Göltürkbükü'ne",
            es: "Aeropuerto de Bodrum a Golturkbuku",
            it: "Aeroporto di Bodrum a Golturkbuku",
            ru: "Аэропорт Бодрум до Гельтюркбюкю",
            zh: "博德鲁姆机场到戈尔特克布库",
            ar: "مطار بودروم إلى غولتوركبوكو",
            linkUrl: "bodrum-airport-to-golturkbuku",
            location: "Bodrum",
            key: "BJV",
            price: 100,
            imageUrl: "/images/popularDestinations/bodrum/bodrum7.webp"

        },
        {
            en: "Bodrum Airport To Ortakent",
            tr: "Bodrum Havalimanı Ortakent'e",
            es: "Aeropuerto de Bodrum a Ortakent",
            it: "Aeroporto di Bodrum a Ortakent",
            ru: "Аэропорт Бодрум до Ортакент",
            zh: "博德鲁姆机场到奥尔塔肯特",
            ar: "مطار بودروم إلى أورتاكينت",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-ortakent",
            key: "BJV",
            price: 100,
            imageUrl: "/images/popularDestinations/bodrum/bodrum8.webp"

        },
        {
            en: "Bodrum Airport To Guvercinlik",
            tr: "Bodrum Havalimanı Güvercinlik'e",
            es: "Aeropuerto de Bodrum a Guvercinlik",
            it: "Aeroporto di Bodrum a Guvercinlik",
            ru: "Аэропорт Бодрум до Гюверджинлик",
            zh: "博德鲁姆机场到居韦尔金利克",
            ar: "مطار بودروم إلى غوفرجينليك",
            linkUrl: "bodrum-airport-to-guvercinlik",
            location: "Bodrum",
            key: "BJV",
            price: 100,
        },

        {
            en: "Bodrum Airport To Akyarlar",
            tr: "Bodrum Havalimanı Akyarlar'a",
            es: "Aeropuerto de Bodrum a Akyarlar",
            it: "Aeroporto di Bodrum a Akyarlar",
            ru: "Аэропорт Бодрум до Акьярлара",
            zh: "博德鲁姆机场到阿克亚拉尔",
            ar: "مطار بودروم إلى أكيارلار",
            linkUrl: "bodrum-airport-to-akyarlar",
            location: "Bodrum",
            key: "BJV",
            price: 100,
        },
        {
            en: "Bodrum Airport To Gumuşluk",
            tr: "Bodrum Havalimanı Gümüşlük'e",
            es: "Aeropuerto de Bodrum a Gumuşluk",
            it: "Aeroporto di Bodrum a Gumuşluk",
            ru: "Аэропорт Бодрум до Гюмюшлюка",
            zh: "博德鲁姆机场到居穆什鲁克",
            ar: "مطار بودروم إلى غوموشلوك",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-gumusluk",
            key: "BJV",
            price: 100,
        },
        {
            en: "Bodrum Airport To Kucukbuk",
            tr: "Bodrum Havalimanı Küçükbük'e",
            es: "Aeropuerto de Bodrum a Kucukbuk",
            it: "Aeroporto di Bodrum a Kucukbuk",
            ru: "Аэропорт Бодрум до Кучюкбюка",
            zh: "博德鲁姆机场到库库克布克",
            ar: "مطار بودروم إلى كوجوكبوك",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-kucukbuk",
            key: "BJV",
            price: 100,
        },
        {
            en: "Bodrum Airport To Turkbuku",
            tr: "Bodrum Havalimanı Türkbükü'ne",
            es: "Aeropuerto de Bodrum a Turkbuku",
            it: "Aeroporto di Bodrum a Turkbuku",
            ru: "Аэропорт Бодрум до Тюркбюкю",
            zh: "博德鲁姆机场到图尔克布克",
            ar: "مطار بودروم إلى توركبوك",
            linkUrl: "bodrum-airport-to-turkbuku",
            location: "Bodrum",
            key: "BJV",
            price: 100,
        },
        {
            en: "Bodrum Airport To Mazi",
            tr: "Bodrum Havalimanı Mazı'ya",
            es: "Aeropuerto de Bodrum a Mazi",
            it: "Aeroporto di Bodrum a Mazi",
            ru: "Аэропорт Бодрум до Мазы",
            zh: "博德鲁姆机场到马兹",
            ar: "مطار بودروم إلى مازي",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-mazi",
            key: "BJV",
            price: 100,
        },
        {
            en: "Bodrum Airport To Kadıkalesi",
            tr: "Bodrum Havalimanı Kadıkalesi'ne",
            es: "Aeropuerto de Bodrum a Kadıkalesi",
            it: "Aeroporto di Bodrum a Kadıkalesi",
            ru: "Аэропорт Бодрум до Кадыкалеси",
            zh: "博德鲁姆机场到卡迪卡莱西",
            ar: "مطار بودروم إلى كاديكاليسي",
            location: "Bodrum",
            linkUrl: "bodrum-airport-to-kadikalesi",
            key: "BJV",
            price: 100,
        },
    ],
    ADB: [
        {
            en: "Izmir Adnan Menderes Airport To Izmir City Center",
            tr: "İzmir Adnan Menderes Havalimanı İzmir Şehir Merkezi'ne",
            es: "Aeropuerto de Izmir Adnan Menderes al Centro de la Ciudad de Izmir",
            it: "Aeroporto di Izmir Adnan Menderes al Centro Città di Izmir",
            ru: "Аэропорт Измир Аднан Мендерес до центра города Измир",
            zh: "伊兹密尔阿德南·门德雷斯机场到伊兹密尔市中心",
            ar: "مطار إزمير عدنان مندريس إلى وسط مدينة إزمير",
            linkUrl: "izmir-adnan-menderes-airport-to-izmir-city-center",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Alsancak",
            tr: "İzmir Adnan Menderes Havalimanı Alsancak'a",
            es: "Aeropuerto de Izmir Adnan Menderes a Alsancak",
            it: "Aeroporto di Izmir Adnan Menderes a Alsancak",
            ru: "Аэропорт Измир Аднан Мендерес до Алсанчака",
            zh: "伊兹密尔阿德南·门德雷斯机场到阿尔桑贾克",
            ar: "مطار إزمير عدنان مندريس إلى ألسانجاك",
            linkUrl: "izmir-adnan-menderes-airport-to-alsancak",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Konak",
            tr: "İzmir Adnan Menderes Havalimanı Konak'a",
            es: "Aeropuerto de Izmir Adnan Menderes a Konak",
            it: "Aeroporto di Izmir Adnan Menderes a Konak",
            ru: "Аэропорт Измир Аднан Мендерес до Конака",
            zh: "伊兹密尔阿德南·门德雷斯机场到科纳克",
            ar: "مطار إزمير عدنان مندريس إلى كوناك",
            linkUrl: "izmir-adnan-menderes-airport-to-konak",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Karsiyaka",
            tr: "İzmir Adnan Menderes Havalimanı Karşıyaka'ya",
            es: "Aeropuerto de Izmir Adnan Menderes a Karsiyaka",
            it: "Aeroporto di Izmir Adnan Menderes a Karsiyaka",
            ru: "Аэропорт Измир Аднан Мендерес до Каршияки",
            zh: "伊兹密尔阿德南·门德雷斯机场到卡尔什亚卡",
            ar: "مطار إزمير عدنان مندريس إلى كارسياكا",
            linkUrl: "izmir-adnan-menderes-airport-to-karsiyaka",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Cesme",
            tr: "İzmir Adnan Menderes Havalimanı Çeşme'ye",
            es: "Aeropuerto de Izmir Adnan Menderes a Cesme",
            it: "Aeroporto di Izmir Adnan Menderes a Cesme",
            ru: "Аэропорт Измир Аднан Мендерес до Чешме",
            zh: "伊兹密尔阿德南·门德雷斯机场到切什梅",
            ar: "مطار إزمير عدنان مندريس إلى تشيشمي",
            linkUrl: "izmir-adnan-menderes-airport-to-cesme",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Alacati",
            tr: "İzmir Adnan Menderes Havalimanı Alaçatı'ya",
            es: "Aeropuerto de Izmir Adnan Menderes a Alacati",
            it: "Aeroporto di Izmir Adnan Menderes a Alacati",
            ru: "Аэропорт Измир Аднан Мендерес до Алачаты",
            zh: "伊兹密尔阿德南·门德雷斯机场到阿拉恰特",
            ar: "مطار إزمير عدنان مندريس إلى ألاكاتي",
            linkUrl: "izmir-adnan-menderes-airport-to-alacati",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Selcuk",
            tr: "İzmir Adnan Menderes Havalimanı Selçuk'a",
            es: "Aeropuerto de Izmir Adnan Menderes a Selcuk",
            it: "Aeroporto di Izmir Adnan Menderes a Selcuk",
            ru: "Аэропорт Измир Аднан Мендерес до Сельчука",
            zh: "伊兹密尔阿德南·门德雷斯机场到塞尔丘克",
            ar: "مطار إزمير عدنان مندريس إلى سلجوق",
            linkUrl: "izmir-adnan-menderes-airport-to-selcuk",
            location: "Izmir",
            key: "ADB",
            price: 100,
        },
        {
            en: "Izmir Adnan Menderes Airport To Ephesus",
            tr: "İzmir Adnan Menderes Havalimanı Efes'e",
            es: "Aeropuerto de Izmir Adnan Menderes a Éfeso",
            it: "Aeroporto di Izmir Adnan Menderes a Efeso",
            ru: "Аэропорт Измир Аднан Мендерес до Эфеса",
            zh: "伊兹密尔阿德南·门德雷斯机场到以弗所",
            ar: "مطار إزمير عدنان مندريس إلى أفسس",
            linkUrl: "izmir-adnan-menderes-airport-to-ephesus",
            location: "Izmir",
            key: "ADB",
            price: 100,
        },
        {
            en: "Izmir Adnan Menderes Airport To Kusadasi",
            tr: "İzmir Adnan Menderes Havalimanı Kuşadası'na",
            es: "Aeropuerto de Izmir Adnan Menderes a Kusadasi",
            it: "Aeroporto di Izmir Adnan Menderes a Kusadasi",
            ru: "Аэропорт Измир Аднан Мендерес до Кушадасы",
            zh: "伊兹密尔阿德南·门德雷斯机场到库沙达瑟",
            ar: "مطار إزمير عدنان مندريس إلى كوساداسي",
            linkUrl: "izmir-adnan-menderes-airport-to-kusadasi",
            location: "Izmir",
            key: "ADB",
            price: 100,
        },
        {
            en: "Izmir Adnan Menderes Airport To Didim",
            tr: "İzmir Adnan Menderes Havalimanı Didim'e",
            es: "Aeropuerto de Izmir Adnan Menderes a Didim",
            it: "Aeroporto di Izmir Adnan Menderes a Didim",
            ru: "Аэропорт Измир Аднан Мендерес до Дидима",
            zh: "伊兹密尔阿德南·门德雷斯机场到迪迪姆",
            ar: "مطار إزمير عدنان مندريس إلى ديديم",
            linkUrl: "izmir-adnan-menderes-airport-to-didim",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },

        {
            en: "Izmir Adnan Menderes Airport To Ozdere",
            tr: "İzmir Adnan Menderes Havalimanı Özdere'ye",
            es: "Aeropuerto de Izmir Adnan Menderes a Ozdere",
            it: "Aeroporto di Izmir Adnan Menderes a Ozdere",
            ru: "Аэропорт Измир Аднан Мендерес до Оздере",
            zh: "伊兹密尔阿德南·门德雷斯机场到奥兹德雷",
            ar: "مطار إزمير عدنان مندريس إلى أوزديري",
            linkUrl: "izmir-adnan-menderes-airport-to-ozdere",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Seferihisar",
            tr: "İzmir Adnan Menderes Havalimanı Seferihisar'a",
            es: "Aeropuerto de Izmir Adnan Menderes a Seferihisar",
            it: "Aeroporto di Izmir Adnan Menderes a Seferihisar",
            ru: "Аэропорт Измир Аднан Мендерес до Сеферихисара",
            zh: "伊兹密尔阿德南·门德雷斯机场到塞费里希萨尔",
            ar: "مطار إزمير عدنان مندريس إلى سفيريهيسار",
            linkUrl: "izmir-adnan-menderes-airport-to-seferihisar",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Foca",
            tr: "İzmir Adnan Menderes Havalimanı Foça'ya",
            es: "Aeropuerto de Izmir Adnan Menderes a Foca",
            it: "Aeroporto di Izmir Adnan Menderes a Foca",
            ru: "Аэропорт Измир Аднан Мендерес до Фочи",
            zh: "伊兹密尔阿德南·门德雷斯机场到福恰",
            ar: "مطار إزمير عدنان مندريس إلى فوكا",
            linkUrl: "izmir-adnan-menderes-airport-to-foca",
            key: "ADB",
            price: 100,
        },
        {
            en: "Izmir Adnan Menderes Airport To Dikili",
            tr: "İzmir Adnan Menderes Havalimanı Dikili'ye",
            es: "Aeropuerto de Izmir Adnan Menderes a Dikili",
            it: "Aeroporto di Izmir Adnan Menderes a Dikili",
            ru: "Аэропорт Измир Аднан Мендерес до Дикили",
            zh: "伊兹密尔阿德南·门德雷斯机场到迪基利",
            ar: "مطار إزمير عدنان مندريس إلى ديكيلي",
            linkUrl: "izmir-adnan-menderes-airport-to-dikili",
            key: "ADB",
            price: 100,
        },
        {
            en: "Izmir Adnan Menderes Airport To Bergama",
            tr: "İzmir Adnan Menderes Havalimanı Bergama'ya",
            es: "Aeropuerto de Izmir Adnan Menderes a Bergama",
            it: "Aeroporto di Izmir Adnan Menderes a Bergama",
            ru: "Аэропорт Измир Аднан Мендерес до Бергамы",
            zh: "伊兹密尔阿德南·门德雷斯机场到贝尔加马",
            ar: "مطار إزمير عدنان مندريس إلى بيرجاما",
            linkUrl: "izmir-adnan-menderes-airport-to-bergama",
            key: "ADB",
            price: 100,
        },
        {
            en: "Izmir Adnan Menderes Airport To Tire",
            tr: "İzmir Adnan Menderes Havalimanı Tire'ye",
            es: "Aeropuerto de Izmir Adnan Menderes a Tire",
            it: "Aeroporto di Izmir Adnan Menderes a Tire",
            ru: "Аэропорт Измир Аднан Мендерес до Тире",
            zh: "伊兹密尔阿德南·门德雷斯机场到提雷",
            ar: "مطار إزمير عدنان مندريس إلى تيره",
            linkUrl: "izmir-adnan-menderes-airport-to-tire",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Torbali",
            tr: "İzmir Adnan Menderes Havalimanı Torbalı'ya",
            es: "Aeropuerto de Izmir Adnan Menderes a Torbali",
            it: "Aeroporto di Izmir Adnan Menderes a Torbali",
            ru: "Аэропорт Измир Аднан Мендерес до Торбалы",
            zh: "伊兹密尔阿德南·门德雷斯机场到托尔巴勒",
            ar: "مطار إزمير عدنان مندريس إلى توربالي",
            linkUrl: "izmir-adnan-menderes-airport-to-torbali",
            key: "ADB",
            price: 100,
            location: "Izmir",

        },
        {
            en: "Izmir Adnan Menderes Airport To Urla",
            tr: "İzmir Adnan Menderes Havalimanı Urla'ya",
            es: "Aeropuerto de Izmir Adnan Menderes a Urla",
            it: "Aeroporto di Izmir Adnan Menderes a Urla",
            ru: "Аэропорт Измир Аднан Мендерес до Урлы",
            zh: "伊兹密尔阿德南·门德雷斯机场到乌尔拉",
            ar: "مطار إزمير عدنان مندريس إلى أورلا",
            linkUrl: "izmir-adnan-menderes-airport-to-urla",
            key: "ADB",
            price: 100,
            // Previous entries...
            location: "Izmir",
        },
    ],
    GZP: [
        {
            en: "Gazipasa-Alanya Airport To Alanya",
            tr: "Gazipaşa-Alanya Havalimanı Alanya'ya",
            es: "Aeropuerto de Gazipasa-Alanya a Alanya",
            it: "Aeroporto di Gazipasa-Alanya a Alanya",
            ru: "Аэропорт Газипаша-Аланья до Аланьи",
            zh: "加济帕萨-阿拉尼亚机场到阿拉尼亚",
            ar: "مطار غازي باشا-ألانيا إلى ألانيا",
            linkUrl: "gazipasa-alanya-airport-to-alanya",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",
        },
        {
            en: "Gazipasa-Alanya Airport To Mahmutlar",
            tr: "Gazipaşa-Alanya Havalimanı Mahmutlar'a",
            es: "Aeropuerto de Gazipasa-Alanya a Mahmutlar",
            it: "Aeroporto di Gazipasa-Alanya a Mahmutlar",
            ru: "Аэропорт Газипаша-Аланья до Махмутлара",
            zh: "加济帕萨-阿拉尼亚机场到马穆特拉尔",
            ar: "مطار غازي باشا-ألانيا إلى محمودلار",
            linkUrl: "gazipasa-alanya-airport-to-mahmutlar",
            price: 100,
            key: "GZP",
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Oba",
            tr: "Gazipaşa-Alanya Havalimanı Oba'ya",
            es: "Aeropuerto de Gazipasa-Alanya a Oba",
            it: "Aeroporto di Gazipasa-Alanya a Oba",
            ru: "Аэропорт Газипаша-Аланья до Обa",
            zh: "加济帕萨-阿拉尼亚机场到奥巴",
            ar: "مطار غازي باشا-ألانيا إلى أوبا",
            linkUrl: "gazipasa-alanya-airport-to-oba",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Kestel",
            tr: "Gazipaşa-Alanya Havalimanı Kestel'e",
            es: "Aeropuerto de Gazipasa-Alanya a Kestel",
            it: "Aeroporto di Gazipasa-Alanya a Kestel",
            ru: "Аэропорт Газипаша-Аланья до Кестеля",
            zh: "加济帕萨-阿拉尼亚机场到克斯特尔",
            ar: "مطار غازي باشا-ألانيا إلى كيستل",
            linkUrl: "gazipasa-alanya-airport-to-kestel",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Tosmur",
            tr: "Gazipaşa-Alanya Havalimanı Tosmur'a",
            es: "Aeropuerto de Gazipasa-Alanya a Tosmur",
            it: "Aeroporto di Gazipasa-Alanya a Tosmur",
            ru: "Аэропорт Газипаша-Аланья до Тосмура",
            zh: "加济帕萨-阿拉尼亚机场到托斯穆尔",
            ar: "مطار غازي باشا-ألانيا إلى توسمور",
            linkUrl: "gazipasa-alanya-airport-to-tosmur",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Avsallar",
            tr: "Gazipaşa-Alanya Havalimanı Avsallar'a",
            es: "Aeropuerto de Gazipasa-Alanya a Avsallar",
            it: "Aeroporto di Gazipasa-Alanya a Avsallar",
            ru: "Аэропорт Газипаша-Аланья до Авсаллара",
            zh: "加济帕萨-阿拉尼亚机场到阿夫萨拉尔",
            ar: "مطار غازي باشا-ألانيا إلى أفسالار",
            linkUrl: "gazipasa-alanya-airport-to-avsallar",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Konakli",
            tr: "Gazipaşa-Alanya Havalimanı Konaklı'ya",
            es: "Aeropuerto de Gazipasa-Alanya a Konakli",
            it: "Aeroporto di Gazipasa-Alanya a Konakli",
            ru: "Аэропорт Газипаша-Аланья до Конаклы",
            zh: "加济帕萨-阿拉尼亚机场到科纳克勒",
            ar: "مطار غازي باشا-ألانيا إلى كوناكلي",
            linkUrl: "gazipasa-alanya-airport-to-konakli",
            price: 100,
            key: "GZP",
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Okurcalar",
            tr: "Gazipaşa-Alanya Havalimanı Okurcalar'a",
            es: "Aeropuerto de Gazipasa-Alanya a Okurcalar",
            it: "Aeroporto di Gazipasa-Alanya a Okurcalar",
            ru: "Аэропорт Газипаша-Аланья до Окурчалара",
            zh: "加济帕萨-阿拉尼亚机场到奥库尔贾拉尔",
            ar: "مطار غازي باشا-ألانيا إلى أوكوركلار",
            linkUrl: "gazipasa-alanya-airport-to-okurcalar",
            key: "GZP",
            price: 100,
        },
        {
            en: "Gazipasa-Alanya Airport To İncekum",
            tr: "Gazipaşa-Alanya Havalimanı İncekum'a",
            es: "Aeropuerto de Gazipasa-Alanya a İncekum",
            it: "Aeroporto di Gazipasa-Alanya a İncekum",
            ru: "Аэропорт Газипаша-Аланья до Инджекума",
            zh: "加济帕萨-阿拉尼亚机场到因杰库姆",
            ar: "مطار غازي باشا-ألانيا إلى إنجيكوم",
            linkUrl: "gazipasa-alanya-airport-to-incekum",
            price: 100,
            key: "GZP",
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Manavgat",
            tr: "Gazipaşa-Alanya Havalimanı Manavgat'a",
            es: "Aeropuerto de Gazipasa-Alanya a Manavgat",
            it: "Aeroporto di Gazipasa-Alanya a Manavgat",
            ru: "Аэропорт Газипаша-Аланья до Манавгата",
            zh: "加济帕萨-阿拉尼亚机场到马纳夫加特",
            ar: "مطار غازي باشا-ألانيا إلى مانافجات",
            linkUrl: "gazipasa-alanya-airport-to-manavgat",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Side",
            tr: "Gazipaşa-Alanya Havalimanı Side'ye",
            es: "Aeropuerto de Gazipasa-Alanya a Side",
            it: "Aeroporto di Gazipasa-Alanya a Side",
            ru: "Аэропорт Газипаша-Аланья до Сиде",
            zh: "加济帕萨-阿拉尼亚机场到西德",
            ar: "مطار غازي باشا-ألانيا إلى سايد",
            linkUrl: "gazipasa-alanya-airport-to-side",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
        {
            en: "Gazipasa-Alanya Airport To Gazipasa Town Center",
            tr: "Gazipaşa-Alanya Havalimanı Gazipaşa Şehir Merkezi'ne",
            es: "Aeropuerto de Gazipasa-Alanya al Centro de la Ciudad de Gazipasa",
            it: "Aeroporto di Gazipasa-Alanya al Centro Città di Gazipasa",
            ru: "Аэропорт Газипаша-Аланья до центра города Газипаша",
            zh: "加济帕萨-阿拉尼亚机场到加济帕萨市中心",
            ar: "مطار غازي باشا-ألانيا إلى وسط مدينة غازي باشا",
            linkUrl: "gazipasa-alanya-airport-to-gazipasa-town-center",
            key: "GZP",
            price: 100,
            location: "Gazipasa-Alanya",

        },
    ],
};

export default airportPoints;


//bir airportsarin hepsi  > /gazipasa-alanya-airport-to-alanya'  falan 
//birde taxi prices  var hansiki navogatorun icinde yerlesen Navbardan gelenOnlarida navigator icine ekleyirik
const pathForCheckingError404 = [
    { path: "/" },
    { path: "/terms" },
    { path: "/fleet" },
    { path: "/manage-booking.html" },
    { path: "/contact-us" },
    { path: "/istanbul-airport-taxi-prices", },
    { path: "/sabiha-gokcen-airport-taxi-prices", },
    { path: "/dalaman-airport-taxi-prices", },
    { path: "/antalya-airport-taxi-prices", },
    { path: "/bodrum-milas-airport-taxi-prices", },
    { path: "/izmir-adnan-menderes-airport-taxi-prices", },
    { path: "/gazipasha-alanya-airport-taxi-prices", },
];

//?Functions Helpers helpers
/**
 * Extracts the `linkUrl` values from the provided data object and returns an array of objects with the `path` property set to the corresponding URL.
 *
 * @param {Object} data - The data object containing the `linkUrl` values.
 * @returns {Array<{ path: string }>} - An array of objects with the `path` property set to the corresponding URL.
 */
const extractLinkUrls = (data) => {
    const urls = [];
    Object.keys(data).forEach((key) => {
        const destinations = data[key];
        destinations.forEach((destination) => {
            if (destination.linkUrl) {
                urls.push({ path: `/${destination.linkUrl}` });
            }
        });
    });
    return urls;
};



/**
 * Checks if the given pathname is a valid path in the application.
 * 
 * @param {string} pathname - The pathname to check.
 * @returns {boolean} - True if the pathname is a valid path, false otherwise.
 */
export const ISvalidPath = (pathname) => {
    return [...pathForCheckingError404, ...extractLinkUrls(airportPoints)].some((route) => route.path.toLowerCase() === pathname.toLowerCase());
}
export const ifItIsQuotationLink = (pathname) => {
    return [...extractLinkUrls(airportPoints)].some((route) => route.path.toLowerCase() === pathname.toLowerCase());
}

/**
 * Finds the matching destination item based on the provided router pathname.
 *
 * @param {string} routerPathname - The pathname to match against the `linkUrl` property of the destination items.
 * @returns {Object} - An object containing the `key` property of the matching destination item, or "IST" if no match is found.
 */
export const findMatchingItem = (routerPathname) => {
    // Combine all destinations into a single array

    let lists = navigator[1].list
    // Find the matching item based on routerPathname
    const matchingItem = lists?.find((destination) => destination.path === `/${routerPathname}`);

    // If a match is found, destructure `location` and return it
    if (matchingItem) {
        const { hasTaxiDeals } = matchingItem;
        return { hasTaxiDeals }; // Return both the location and the full item if needed
    }

    // If no match is found, return null or handle accordingly
    return { hasTaxiDeals: "IST" };
};
